### ISSUE TITLE
Ungewöhnliche Variablen Benennung

### ISSUE THREAD

**Issue by ivenassenkamp** [BinGutDeutsch/Bugreport-Discord-Bot#2]
https://github.com/BinGutDeutsch/Bugreport-Discord-Bot/blob/0a9bfede2a7d051b4a60ff87476efef6a8156f35/BugReporter/src/main/java/main/DiscordBot.java#L28
Auch wenn es nicht direkt verboten ist, ist es unüblich Variablen mit Unterstrichen zu benennen.
Daher würde ich vorschlagen, die `m_` Präfixe vor einigen Variablen zu entfernen, da mir persönlich auch keinen nutzen dieses Präfixes ersichtlich ist, vielleicht kannst du mich ja dementsprechend aufklären.

**Comment by BinGutDeutsch** [comment]
Die Benennung der Membervariablen mit `m_` hab ich mir durch die aktuelle Firma in der ich arbeite angewöhnt. Dort ist es firmenweiter Standard diese so zu benennen um deutlich zu zeigen, dass es eine Membervariable ist.

**Comment by ivenassenkamp** [comment]
Und du programmierst dort auch mit Java 🤔
Weil den Begriff `Membervariable` hab ich bezogen auf Java jetzt noch nicht gehört, ich kenne nur die Benennung Feld bzw. Field

**Comment by BinGutDeutsch** [comment]
Ja dort arbeite ich, unter anderem, auch mit Java. Die, wie du nennst Fields, haben ja verschiedene Namen. Ich hab sie als Attribute kennengelernt und inzwischen kenn ich sie als Membervariable. Ich habe ehrlich gesagt auch noch nichts von Field gehört 😄
