### ISSUE TITLE
Felder in BugchannelManager "besser" deklarieren

### ISSUE THREAD

**Issue by ivenassenkamp** [BinGutDeutsch/Bugreport-Discord-Bot#3]
https://github.com/BinGutDeutsch/Bugreport-Discord-Bot/blob/0a9bfede2a7d051b4a60ff87476efef6a8156f35/BugReporter/src/main/java/main/BugchannelManager.java#L16-L35
Wenn es nicht mehr möglich ist, die Felder zu verändern, würde ich vorschlagen, die Felder dann `public`, `static` und `final` zu machen, dann sparst du dir eine Instanz der Klasse und kannst direkt auf die Felder zugreifen.
Vergiss dann nur nicht, die Felder auch im "Upper Snake Case" zu benennen c:

**Comment by ivenassenkamp** [comment]
Um da aber noch eine bessere Lösung in meinen Augen zuzugeben, würde ich vorschlagen, dass man für Channel Namen, Rolle-Namen usw. eine Config macht, in welchem die Channel-IDs, Role-ID usw. gespeichert werden, damit der Bot immer wieder weiß welche Kanäle er bewachen muss und welche Rolle was darf und man es nicht fest im Code verankert.

**Comment by BinGutDeutsch** [comment]
Die Channel sowie die Rolle wurden in eine Config ausgelagert.
