### ISSUE TITLE
Ungewollte Exception beim verwalten der Reports

### ISSUE THREAD

**Issue by ivenassenkamp** [BinGutDeutsch/Bugreport-Discord-Bot#5]
Reagiert man mit einer der Buttons, wird überprüft, ob jemand die Rolle "Bugs verwalten" hat und dann wird das erstbeste Ergebnis aus `Guild#getRolesByName` genommen. Existiert keine, fliegt wieder 'ne Exception und die Interaktion schlägt fehl und es passiert nichts. Ist ziemlich unpraktisch, wenn man den Bot nicht richtig eingestellt hat und abgesehen von der Exception keine Rückmeldung von sich gibt.
Da wäre wie in https://github.com/BinGutDeutsch/Bugreport-Discord-Bot/issues/3 beschrieben eine Config was ganz feines, wo man die Role ID angeben kann 😊

**Comment by BinGutDeutsch** [comment]
Da es keine Bugreports geben kann, wenn der Setup nicht durchgelaufen ist, ist es auch nicht möglich, dass die Rolle nicht existiert. Was anderes ist es natürlich, wenn die Rolle manuell wieder gelöscht wird. Aber da der Bot vorerst nur für MyPvP geplant ist, dachte ich nicht, dass ich dafür auch noch eine Prüfung machen muss 😄 

Über die Config habe ich bereits auch schon nachgedacht und ich sehe nichts was dagegen spricht.
